<?php

namespace Ultracache;

//require_once dirname(__FILE__) . '/../../../src/Ultracache/Ultracache.php';

/**
 * Test class for Ultracache.
 * Generated by PHPUnit on 2013-01-03 at 00:12:28.
 */
class UltracacheTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Ultracache
	 */
	protected $Object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->Object = new Ultracache(array(
			'remote' => array('onetime' => array()),
			'local' => array('onetime' => array()),
		));
		$this->Object->set('test','test set');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Ultracache\Ultracache::get
	 * @todo Implement testGet().
	 */
	public function testGet() {
		
		$cache = $this->Object->get('test');
		$this->assertEquals($cache, 'test set');

	}
//
//	/**
//	 * @covers Ultracache\Ultracache::set
//	 * @todo Implement testSet().
//	 */
//	public function testSet() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}
//
//	/**
//	 * @covers Ultracache\Ultracache::delete
//	 * @todo Implement testDelete().
//	 */
//	public function testDelete() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}
//
//	/**
//	 * @covers Ultracache\Ultracache::sync
//	 * @todo Implement testSync().
//	 */
//	public function testSync() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}

}